import type { DecisionPlayerPhaseWorkspace } from "../../../types";

export const AUSTRIA_DECISION_DEMO_WORKSPACE: DecisionPlayerPhaseWorkspace = {
  activeEvents: [],
  budgetPools: {
    domesticMarket: 10,
    factory: 10,
    governmentFiscal: 15,
  },
  countryCode: "austria",
  countryLabel: "奥地利",
  domesticMarketActions: [
    {
      actionId: "market_fair",
      cost: 5,
      description: "举办商品博览会，低成本扩大国内市场承接能力。",
      label: "博览会",
      lockedReason: null,
      effects: { domesticMarketCapacityDelta: 2 },
    },
    {
      actionId: "rural_development",
      cost: 6,
      description: "投资乡村基建，大幅扩大市场覆盖面但不直接提价。",
      label: "乡村开发",
      lockedReason: null,
      effects: { domesticMarketCapacityDelta: 3 },
    },
    {
      actionId: "consumer_subsidy",
      cost: 8,
      description: "向国内市场追加补贴，提高本回合国内市场承接能力。",
      label: "消费补贴",
      lockedReason: "需要研究「市场经济」",
      effects: { domesticMarketCapacityDelta: 2, domesticPriceBonusDelta: 1 },
    },
    {
      actionId: "import_substitution",
      cost: 9,
      description: "限制进口同类商品，让国内收购价格显著上升。",
      label: "进口替代",
      lockedReason: "需要研究「市场经济」",
      effects: { domesticMarketCapacityDelta: 1, domesticPriceBonusDelta: 2 },
    },
    {
      actionId: "public_works",
      cost: 10,
      description: "投入基础设施，稳住内需并改善国内收购价格。",
      label: "公共工程",
      lockedReason: "需要研究「消费社会」",
      effects: { domesticMarketCapacityDelta: 2, domesticPriceBonusDelta: 2 },
    },
    {
      actionId: "luxury_promotion",
      cost: 12,
      description: "培育高端消费市场，大幅提高国内商品收购价格。",
      label: "奢侈品推广",
      lockedReason: "需要研究「消费社会」",
      effects: { domesticPriceBonusDelta: 4 },
    },
  ],
  expansionOptions: [
    {
      capacityDelta: 1,
      lockedReason: null,
      maxQuantity: 1,
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 8,
    },
  ],
  governmentActions: {
    pointPurchaseCosts: {
      military: 10,
      tech: 2,
    },
    strategies: [
      {
        actionId: "trade_agreement",
        cost: 6,
        description: "签订双边贸易协定，改善海外出售价格。",
        label: "贸易协定",
        lockedReason: null,
        militaryPointCost: 0,
        militaryPointDelta: 0,
        ratioDelta: {},
        techPointCost: 0,
        techPointDelta: 0,
        effects: { overseasMarketCapacityDelta: 1, overseasPriceBonusDelta: 2 },
      },
      {
        actionId: "expand_shipping_lines",
        cost: 10,
        description: "开辟新航线，提升海外市场能力。",
        label: "扩展航线",
        lockedReason: "需要研究「行政改革」",
        militaryPointCost: 0,
        militaryPointDelta: 0,
        ratioDelta: {
          domesticMarket: -0.2,
          governmentFiscal: 0.2,
        },
        techPointCost: 0,
        techPointDelta: 0,
        effects: { overseasMarketCapacityDelta: 1, overseasPriceBonusDelta: 1 },
      },
      {
        actionId: "domestic_stimulus",
        cost: 10,
        description: "推行内需扶持政策，把收入结构拉回国内消费方向。",
        label: "内需刺激",
        lockedReason: null,
        militaryPointCost: 0,
        militaryPointDelta: 0,
        ratioDelta: {
          domesticMarket: 0.3,
          governmentFiscal: -0.3,
        },
        techPointCost: 0,
        techPointDelta: 0,
        effects: { domesticMarketCapacityDelta: 3, domesticPriceBonusDelta: 1 },
      },
      {
        actionId: "industrial_policy",
        cost: 12,
        description: "推动产业升级，提升国内外商品附加值，获得科技点数。",
        label: "产业政策",
        lockedReason: "需要研究「行政改革」",
        militaryPointCost: 0,
        militaryPointDelta: 0,
        ratioDelta: {
          factory: 0.2,
          governmentFiscal: -0.2,
        },
        techPointCost: 0,
        techPointDelta: 1,
        effects: { domesticPriceBonusDelta: 1, overseasPriceBonusDelta: 1 },
      },
      {
        actionId: "naval_modernization",
        cost: 14,
        description: "推动海军升级，大幅强化海外投射能力，获得科技点数。",
        label: "海军现代化",
        lockedReason: "需要研究「帝国体制」",
        militaryPointCost: 0,
        militaryPointDelta: 0,
        ratioDelta: {
          domesticMarket: -0.1,
          governmentFiscal: 0.1,
        },
        techPointCost: 0,
        techPointDelta: 1,
        effects: { overseasMarketCapacityDelta: 2, overseasPriceBonusDelta: 1 },
      },
    ],
  },
  incomeAllocationRatio: {
    domesticMarket: 3,
    factory: 2.5,
    governmentFiscal: 4.5,
  },
  militaryWorkspace: {
    militaryPoints: 1,
    army: {
      infantry: 1,
    },
    navy: {
      fleets: 0,
    },
    controlledRegions: 0,
    establishedDiplomacy: [],
    overseasCapacity: 1,
    regionAccessStatus: [
      {
        regionId: "africa",
        label: "非洲",
        accessLevel: "concession",
        isAccessible: true,
        isDiplomacyEstablished: false,
        acceptedGoods: ["rubber", "cotton", "minerals"],
        isColonized: false,
        controller: null,
      },
      {
        regionId: "middle_east",
        label: "中东",
        accessLevel: "concession",
        isAccessible: true,
        isDiplomacyEstablished: false,
        acceptedGoods: ["oil", "tea"],
        isColonized: false,
        controller: null,
      },
      {
        regionId: "europe",
        label: "欧洲",
        accessLevel: "open",
        isAccessible: true,
        isDiplomacyEstablished: false,
        acceptedGoods: ["steel", "coal"],
        isColonized: false,
        controller: null,
      },
    ],
    colonizationCapability: {
      isUnlocked: false,
      unlockCost: 10,
      militaryPointCost: 3,
      incomePerColonyPerRound: 5,
      maxColonizationsPerRound: 1,
    },
    colonizationOptions: [],
    oceanNodes: [],
    availableMilitaryActions: [
      {
        actionId: "naval_drill",
        label: "海军演练",
        cost: 6,
        maxPerRound: 2,
        description: "开展海军演练，提升军事点并扩展海外市场承接力。",
        effects: { militaryPointsDelta: 1, overseasMarketCapacityDelta: 1 },
      },
      {
        actionId: "recruit_infantry",
        label: "征募步兵",
        cost: 4,
        maxPerRound: 3,
        description: "征募步兵部队，增加军事影响力。",
        effects: { militaryPointsDelta: 1 },
      },
      {
        actionId: "train_artillery",
        label: "训练炮兵",
        cost: 8,
        maxPerRound: 1,
        description: "训练重型炮兵，快速提升军事力量。",
        effects: { militaryPointsDelta: 2 },
      },
      {
        actionId: "colonial_expedition",
        label: "殖民远征",
        cost: 20,
        maxPerRound: 1,
        description: "组织大规模远征，强化海外控制与承接能力。",
        effects: { overseasMarketCapacityDelta: 2, controlledRegionsDelta: 1 },
      },
    ],
    availableDiplomacyActions: [
      {
        actionId: "establish_africa",
        label: "与非洲建交",
        cost: 7,
        targetRegion: "africa",
        targetRegionLabel: "非洲",
        description: "与非洲建立外交关系，永久开放贸易通道。",
        isEstablished: false,
      },
      {
        actionId: "establish_middle_east",
        label: "与中东建交",
        cost: 7,
        targetRegion: "middle_east",
        targetRegionLabel: "中东",
        description: "与中东建立外交关系，永久开放贸易通道。",
        isEstablished: false,
      },
    ],
  },
  researchWorkspace: {
    techPoints: 2,
    talentBranches: [
      {
        branchId: "industry",
        label: "工业",
        nodes: [
          {
            nodeId: "ind_basic_metallurgy",
            label: "基础冶金",
            techPointCost: 1,
            description: "掌握基础冶金工艺，提升手工业基础产能。 效果：手工业产能 +1。",
            permanentEffects: { handicraftCapacityDelta: 1 },
            isUnlocked: false,
            canUnlock: true,
          },
        ],
      },
    ],
    unlockedTalentCount: 0,
  },
  militaryPoints: 1,
  nationalAbility: {
    abilityId: "ausgleich_1867",
    description: "本回合同时提升国内与海外承接能力。",
    isAvailable: true,
    label: "1867年妥协",
    requiresTargetIdeology: false,
  },
  newFactoryOptions: [
    {
      capacityDelta: 1,
      lockedReason: "预算不足",
      maxQuantity: 0,
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 12,
    },
  ],
  productionOptions: [
    {
      domesticReferencePrice: 3,
      goodsId: "grain",
      label: "粮食",
      lockedReason: null,
      maxQuantity: 1,
      overseasReferencePriceMax: 5,
      overseasReferencePriceMin: 2,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 1,
      unitOutput: 1,
      usageHint: "稳内需、低风险。",
    },
    {
      domesticReferencePrice: 2,
      goodsId: "cotton",
      label: "棉花",
      lockedReason: "需要研究「纺织技术」",
      maxQuantity: 0,
      overseasReferencePriceMax: 7,
      overseasReferencePriceMin: 4,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 1,
      unitOutput: 1,
      usageHint: "早期出口原料。",
    },
    {
      domesticReferencePrice: 3,
      goodsId: "tea",
      label: "茶叶",
      lockedReason: "需要研究「茶道工艺」",
      maxQuantity: 0,
      overseasReferencePriceMax: 8,
      overseasReferencePriceMin: 5,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 2,
      unitOutput: 1,
      usageHint: "早期高外销。",
    },
    {
      domesticReferencePrice: 4,
      goodsId: "coal",
      label: "煤炭",
      lockedReason: "该国无该商品生产资格",
      maxQuantity: 0,
      overseasReferencePriceMax: 7,
      overseasReferencePriceMin: 4,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 2,
      unitOutput: 1,
      usageHint: "工业基础品。",
    },
    {
      domesticReferencePrice: 3,
      goodsId: "minerals",
      label: "矿产",
      lockedReason: null,
      maxQuantity: 1,
      overseasReferencePriceMax: 8,
      overseasReferencePriceMin: 5,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 2,
      unitOutput: 1,
      usageHint: "中性外销品。",
    },
    {
      domesticReferencePrice: 6,
      goodsId: "steel",
      label: "钢铁",
      lockedReason: "需要研究「珍妮纺织机」",
      maxQuantity: 0,
      overseasReferencePriceMax: 10,
      overseasReferencePriceMin: 7,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "mechanized",
      routeLabel: "机械化",
      unitBudgetCost: 3,
      unitOutput: 1,
      usageHint: "工业主力品。",
    },
    {
      domesticReferencePrice: 5,
      goodsId: "silk",
      label: "丝绸",
      lockedReason: "需要研究「珍妮纺织机」",
      maxQuantity: 0,
      overseasReferencePriceMax: 11,
      overseasReferencePriceMin: 8,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "mechanized",
      routeLabel: "机械化",
      unitBudgetCost: 3,
      unitOutput: 1,
      usageHint: "奢侈出口品。",
    },
    {
      domesticReferencePrice: 7,
      goodsId: "oil",
      label: "石油",
      lockedReason: "需要研究「蒸汽引擎」",
      maxQuantity: 0,
      overseasReferencePriceMax: 11,
      overseasReferencePriceMin: 8,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "steam",
      routeLabel: "蒸汽工业",
      unitBudgetCost: 4,
      unitOutput: 1,
      usageHint: "中后期高值品。",
    },
    {
      domesticReferencePrice: 8,
      goodsId: "rubber",
      label: "橡胶",
      lockedReason: "需要研究「电气化」",
      maxQuantity: 0,
      overseasReferencePriceMax: 12,
      overseasReferencePriceMin: 9,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "electrified",
      routeLabel: "电气工业",
      unitBudgetCost: 5,
      unitOutput: 1,
      usageHint: "终盘高值品。",
    },
  ],
  routeSummaries: [
    {
      availableBatchesThisRound: 1,
      currentCapacity: 1,
      pendingCapacity: 0,
      routeId: "handicraft",
      routeLabel: "手工业",
    },
    {
      availableBatchesThisRound: 0,
      currentCapacity: 0,
      pendingCapacity: 0,
      routeId: "mechanized",
      routeLabel: "机械化",
    },
  ],
  techPoints: 0,
  techTree: {
    chains: [
      {
        chainId: "industrial",
        label: "工业链",
        techs: [
          { techId: "textile_tech", label: "纺织技术", threshold: 3, progress: 0, effectiveThreshold: 3, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "tea_craft", label: "茶道工艺", threshold: 3, progress: 0, effectiveThreshold: 3, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "mining_dev", label: "矿业开发", threshold: 3, progress: 0, effectiveThreshold: 3, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "spinning_jenny", label: "珍妮纺织机", threshold: 5, progress: 0, effectiveThreshold: 5, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "steam_engine", label: "蒸汽引擎", threshold: 8, progress: 0, effectiveThreshold: 8, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "electrification", label: "电气化", threshold: 12, progress: 0, effectiveThreshold: 12, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
        ],
      },
      {
        chainId: "governance",
        label: "治理链",
        techs: [
          { techId: "admin_reform", label: "行政改革", threshold: 4, progress: 0, effectiveThreshold: 4, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "imperial_system", label: "帝国体制", threshold: 6, progress: 0, effectiveThreshold: 6, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "global_hegemony", label: "全球霸权", threshold: 10, progress: 0, effectiveThreshold: 10, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
        ],
      },
      {
        chainId: "commerce",
        label: "商业链",
        techs: [
          { techId: "market_economy", label: "市场经济", threshold: 3, progress: 0, effectiveThreshold: 3, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "consumer_society", label: "消费社会", threshold: 5, progress: 0, effectiveThreshold: 5, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
        ],
      },
    ],
    researchFacilities: 1,
    facilityCost: 10,
    progressPerFacility: 2,
    activeResearch: null,
  },
  upgradeOptions: [
    {
      capacityDelta: 1,
      lockedReason: "需要研究「珍妮纺织机」",
      maxQuantity: 0,
      routeId: "mechanized",
      routeLabel: "机械化",
      sourceRouteId: "handicraft",
      sourceRouteLabel: "手工业",
      unitBudgetCost: 10,
    },
  ],
};
