import i18n from "../../../i18n";
import type { DecisionPlayerPhaseWorkspace } from "../../../types";

export const AUSTRIA_DECISION_DEMO_WORKSPACE: DecisionPlayerPhaseWorkspace = {
  activeEvents: [],
  budgetPools: {
    domesticMarket: 10,
    factory: 10,
    governmentFiscal: 15,
  },
  countryCode: "austria",
  countryLabel: i18n.t("game:country.austria"),
  domesticMarketActions: [],
  expansionOptions: [
    {
      capacityDelta: 1,
      lockedReason: null,
      maxQuantity: 1,
      routeId: "handicraft",
      routeLabel: i18n.t("game:productionRoute.handicraft"),
      unitBudgetCost: 8,
    },
  ],
  governmentActions: {
    pointPurchaseCosts: {
      military: 6,
      tech: 2,
    },
    strategies: [
      {
        actionId: "expand_workshop",
        cost: 4,
        description: i18n.t("game:demo.expandWorkshopDesc", "扩建民间手工作坊，增加后续手工业产能。"),
        label: i18n.t("game:demo.expandWorkshop", "扩建作坊"),
        lockedReason: null,
        effects: { handicraftCapacityDelta: 1 },
      },
      {
        actionId: "market_fair",
        cost: 5,
        description: i18n.t("game:demo.marketFairDesc", "举办商品博览会，永久提高国内市场承接上限。"),
        label: i18n.t("game:demo.marketFair", "博览会"),
        lockedReason: null,
        effects: { domesticMarketCapacityDelta: 2 },
      },
      {
        actionId: "rural_development",
        cost: 6,
        description: i18n.t("game:demo.ruralDevDesc", "投资乡村基建，大幅扩大本回合国内承接量。"),
        label: i18n.t("game:demo.ruralDev", "乡村开发"),
        lockedReason: null,
        effects: { domesticMarketCapacityDelta: 3 },
      },
      {
        actionId: "consumer_subsidy",
        cost: 8,
        description: i18n.t("game:demo.consumerSubsidyDesc", "追加消费补贴，同时提高本回合国内承接量和收购价格。"),
        label: i18n.t("game:demo.consumerSubsidy", "消费补贴"),
        lockedReason: i18n.t("game:demo.needMarketEconomy", "需要研究「市场经济」"),
        effects: { domesticMarketCapacityDelta: 2, domesticPriceBonusDelta: 1 },
      },
      {
        actionId: "import_substitution",
        cost: 7,
        description: i18n.t("game:demo.importSubDesc", "限制进口替代品，提高本回合国内承接量和收购价格。"),
        label: i18n.t("game:demo.importSub", "进口替代"),
        lockedReason: i18n.t("game:demo.needMarketEconomy", "需要研究「市场经济」"),
        effects: { domesticMarketCapacityDelta: 1, domesticPriceBonusDelta: 2 },
      },
      {
        actionId: "public_works",
        cost: 8,
        description: i18n.t("game:demo.publicWorksDesc", "投入公共工程，同时抬高本回合内需承接和价格。"),
        label: i18n.t("game:demo.publicWorks", "公共工程"),
        lockedReason: i18n.t("game:demo.needConsumerSociety", "需要研究「消费社会」"),
        effects: { domesticMarketCapacityDelta: 2, domesticPriceBonusDelta: 2 },
      },
      {
        actionId: "luxury_promotion",
        cost: 9,
        description: i18n.t("game:demo.luxuryPromoDesc", "培育高端消费市场，提高国内商品收购价格，但收益不再压过完整军事路线。"),
        label: i18n.t("game:demo.luxuryPromo", "奢侈品推广"),
        lockedReason: i18n.t("game:demo.needConsumerSociety", "需要研究「消费社会」"),
        effects: { domesticPriceBonusDelta: 2 },
      },
      {
        actionId: "infrastructure_investment",
        cost: 10,
        description: i18n.t("game:demo.infraInvestDesc", "投资基础设施，增加后续手工业产能。"),
        label: i18n.t("game:demo.infraInvest", "基础设施投资"),
        lockedReason: i18n.t("game:demo.needConsumerSociety", "需要研究「消费社会」"),
        effects: { handicraftCapacityDelta: 2 },
      },
      {
        actionId: "trade_hub",
        cost: 15,
        description: i18n.t("game:demo.tradeHubDesc", "建设商贸枢纽，永久扩展海外市场承接上限。"),
        label: i18n.t("game:demo.tradeHub", "商贸枢纽"),
        lockedReason: i18n.t("game:demo.needGlobalHegemony", "需要研究「全球霸权」"),
        effects: { overseasMarketCapacityDelta: 1 },
      },
      {
        actionId: "expand_research",
        cost: 10,
        description: i18n.t("game:demo.expandResearchDesc", "建设一所研究院，永久提高研究推进速度。"),
        label: i18n.t("game:demo.expandResearch", "建立研究院"),
        lockedReason: null,
        effects: { researchFacilityDelta: { academy: 1 } },
      },
    ],
  },
  incomeAllocationRatio: {
    domesticMarket: 3,
    factory: 2.5,
    governmentFiscal: 4.5,
  },
  domesticMarketCapacity: 4,
  overseasMarketCapacity: 1,
  phase1Economy: {
    capacityByMode: { handicraft: 1 },
    rawMaterials: 3,
    goodsInventory: 2,
    productionModes: [],
    domesticDemand: 4,
    equilibriumPrice: 3,
    domesticBasePricePreview: 3,
    domesticPriceBeforeCap: 3,
    domesticPricePreview: 3,
    domesticPriceBonus: 0,
    overseasPriceBonus: 0,
    domesticPriceCeiling: 8,
    overseasPriceCeiling: 18,
    investmentPool: 10,
    incomeAllocationRatio: {
      domesticMarket: 3,
      factory: 2.5,
      governmentFiscal: 4.5,
    },
    marketMetrics: {},
    consumptionPool: 10,
  },
  militaryWorkspace: {
    armyCap: 3,
    army: {
      infantry: 1,
    },
    navy: {
      fleets: 0,
    },
    controlledRegions: 0,
    establishedDiplomacy: [],
    overseasCapacity: 1,
    regionAccessStatus: [
      {
        regionId: "africa",
        label: i18n.t("game:region.africa"),
        accessLevel: "concession",
        isAccessible: true,
        lockReason: null,
        isDiplomacyEstablished: false,
        acceptedGoods: ["rubber", "cotton", "minerals"],
        priceMultiplier: 1,
        isColonized: false,
        controller: null,
      },
      {
        regionId: "middle_east",
        label: i18n.t("game:region.middle_east"),
        accessLevel: "concession",
        isAccessible: true,
        lockReason: null,
        isDiplomacyEstablished: false,
        acceptedGoods: ["oil", "tea"],
        priceMultiplier: 1,
        isColonized: false,
        controller: null,
      },
      {
        regionId: "europe",
        label: i18n.t("game:region.europe"),
        accessLevel: "open",
        isAccessible: true,
        lockReason: null,
        isDiplomacyEstablished: false,
        acceptedGoods: ["steel", "coal"],
        priceMultiplier: 1,
        isColonized: false,
        controller: null,
      },
    ],
    colonizationCapability: {
      isUnlocked: false,
      unlockCost: 0,
      budgetCost: 0,
      incomePerColonyPerRound: 0,
      maxColonizationsPerRound: 0,
    },
    colonizationOptions: [],
    oceanNodes: [],
    availableMilitaryActions: [
      {
        actionId: "naval_drill",
        label: i18n.t("game:demo.navalDrill", "海军演练"),
        cost: 1,
        maxPerRound: 2,
        description: i18n.t("game:demo.navalDrillDesc", "消耗政府财政开展海军演练，永久提高海外市场承接上限。"),
        effects: { overseasMarketCapacityDelta: 1 },
      },
      {
        actionId: "recruit_infantry",
        label: i18n.t("game:demo.recruitInfantry", "征募步兵"),
        cost: 1,
        maxPerRound: 3,
        description: i18n.t("game:demo.recruitInfantryDesc", "消耗军事点征募步兵部队。"),
        effects: { armyDelta: { infantry: 1 } },
      },
      {
        actionId: "train_artillery",
        label: i18n.t("game:demo.trainArtillery", "训练炮兵"),
        cost: 2,
        maxPerRound: 1,
        description: i18n.t("game:demo.trainArtilleryDesc", "消耗军事点训练重型炮兵。"),
        effects: { armyDelta: { artillery: 1 } },
      },
    ],
    availableDiplomacyActions: [
      {
        actionId: "establish_africa",
        label: i18n.t("game:demo.diplomacyAfrica", "与非洲建交"),
        cost: 7,
        targetRegion: "africa",
        targetRegionLabel: i18n.t("game:region.africa"),
        description: i18n.t("game:demo.diplomacyAfricaDesc", "与非洲建立外交关系，永久开放贸易通道。"),
        isEstablished: false,
      },
      {
        actionId: "establish_middle_east",
        label: i18n.t("game:demo.diplomacyMiddleEast", "与中东建交"),
        cost: 7,
        targetRegion: "middle_east",
        targetRegionLabel: i18n.t("game:region.middle_east"),
        description: i18n.t("game:demo.diplomacyMiddleEastDesc", "与中东建立外交关系，永久开放贸易通道。"),
        isEstablished: false,
      },
    ],
  },
  researchWorkspace: {
    techPoints: 2,
    talentBranches: [
      {
        branchId: "industry",
        label: i18n.t("game:demo.industryBranch", "工业"),
        nodes: [
          {
            nodeId: "ind_basic_metallurgy",
            label: i18n.t("game:demo.workshopReform", "工坊整顿"),
            techPointCost: 1,
            description: i18n.t("game:demo.workshopReformDesc", "整顿分散工坊和账房流程，稳定扩大早期手工业产能。 效果：手工业产能 +1。"),
            permanentEffects: { handicraftCapacityDelta: 1 },
            isUnlocked: false,
            canUnlock: true,
          },
        ],
      },
    ],
    unlockedTalentCount: 0,
  },
  armyCap: 3,
  nationalAbility: {
    abilityId: "ausgleich_1867",
    description: i18n.t("game:demo.ausgleich1867Desc", "本回合同时提升国内与海外承接能力。"),
    isAvailable: true,
    label: i18n.t("game:demo.ausgleich1867", "1867年妥协"),
    requiresTargetIdeology: false,
  },
  newFactoryOptions: [
    {
      capacityDelta: 2,
      lockedReason: i18n.t("game:demo.budgetInsufficient", "预算不足"),
      maxQuantity: 0,
      routeId: "handicraft",
      routeLabel: i18n.t("game:productionRoute.handicraft"),
      unitBudgetCost: 12,
    },
  ],
  factoryActions: [
    {
      actionId: "factory_raw_procurement",
      label: i18n.t("game:demo.rawProcurement", "原料统购"),
      cost: 3,
      description: i18n.t("game:demo.rawProcurementDesc", "由工厂直接组织原料采购，立刻补充原材料。"),
      lockedReason: null,
      effects: { rawMaterialsDelta: 4 },
    },
  ],
  productionOptions: [
    {
      domesticReferencePrice: 3,
      goodsId: "grain",
      label: i18n.t("game:goods.grain"),
      lockedReason: null,
      maxQuantity: 1,
      overseasReferencePriceMax: 5,
      overseasReferencePriceMin: 2,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: i18n.t("game:productionRoute.handicraft"),
      unitBudgetCost: 1,
      unitOutput: 1,
      usageHint: i18n.t("game:demo.usageGrain", "稳内需、低风险。"),
    },
    {
      domesticReferencePrice: 2,
      goodsId: "cotton",
      label: i18n.t("game:goods.cotton"),
      lockedReason: i18n.t("game:demo.needTextileTech", "需要研究「纺织技术」"),
      maxQuantity: 0,
      overseasReferencePriceMax: 7,
      overseasReferencePriceMin: 4,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: i18n.t("game:productionRoute.handicraft"),
      unitBudgetCost: 1,
      unitOutput: 1,
      usageHint: i18n.t("game:demo.usageCotton", "早期出口原料。"),
    },
    {
      domesticReferencePrice: 3,
      goodsId: "tea",
      label: i18n.t("game:goods.tea"),
      lockedReason: i18n.t("game:demo.needTeaCraft", "需要研究「茶道工艺」"),
      maxQuantity: 0,
      overseasReferencePriceMax: 8,
      overseasReferencePriceMin: 5,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: i18n.t("game:productionRoute.handicraft"),
      unitBudgetCost: 2,
      unitOutput: 1,
      usageHint: i18n.t("game:demo.usageTea", "早期高外销。"),
    },
    {
      domesticReferencePrice: 4,
      goodsId: "coal",
      label: i18n.t("game:goods.coal"),
      lockedReason: i18n.t("game:demo.noProductionQualification", "该国无该商品生产资格"),
      maxQuantity: 0,
      overseasReferencePriceMax: 7,
      overseasReferencePriceMin: 4,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: i18n.t("game:productionRoute.handicraft"),
      unitBudgetCost: 2,
      unitOutput: 1,
      usageHint: i18n.t("game:demo.usageCoal", "工业基础品。"),
    },
    {
      domesticReferencePrice: 3,
      goodsId: "minerals",
      label: i18n.t("game:goods.minerals"),
      lockedReason: null,
      maxQuantity: 1,
      overseasReferencePriceMax: 8,
      overseasReferencePriceMin: 5,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: i18n.t("game:productionRoute.handicraft"),
      unitBudgetCost: 2,
      unitOutput: 1,
      usageHint: i18n.t("game:demo.usageMinerals", "中性外销品。"),
    },
    {
      domesticReferencePrice: 6,
      goodsId: "steel",
      label: i18n.t("game:goods.steel"),
      lockedReason: i18n.t("game:demo.needSpinningJenny", "需要研究「珍妮纺织机」"),
      maxQuantity: 0,
      overseasReferencePriceMax: 10,
      overseasReferencePriceMin: 7,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "mechanized",
      routeLabel: i18n.t("game:productionRoute.mechanized"),
      unitBudgetCost: 3,
      unitOutput: 1,
      usageHint: i18n.t("game:demo.usageSteel", "工业主力品。"),
    },
    {
      domesticReferencePrice: 5,
      goodsId: "silk",
      label: i18n.t("game:goods.silk"),
      lockedReason: i18n.t("game:demo.needSpinningJenny", "需要研究「珍妮纺织机」"),
      maxQuantity: 0,
      overseasReferencePriceMax: 11,
      overseasReferencePriceMin: 8,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "mechanized",
      routeLabel: i18n.t("game:productionRoute.mechanized"),
      unitBudgetCost: 3,
      unitOutput: 1,
      usageHint: i18n.t("game:demo.usageSilk", "奢侈出口品。"),
    },
    {
      domesticReferencePrice: 7,
      goodsId: "oil",
      label: i18n.t("game:goods.oil"),
      lockedReason: i18n.t("game:demo.needSteamEngine", "需要研究「蒸汽引擎」"),
      maxQuantity: 0,
      overseasReferencePriceMax: 11,
      overseasReferencePriceMin: 8,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "steam",
      routeLabel: i18n.t("game:productionRoute.steam"),
      unitBudgetCost: 4,
      unitOutput: 1,
      usageHint: i18n.t("game:demo.usageOil", "中后期高值品。"),
    },
    {
      domesticReferencePrice: 8,
      goodsId: "rubber",
      label: i18n.t("game:goods.rubber"),
      lockedReason: i18n.t("game:demo.needElectrification", "需要研究「电气化」"),
      maxQuantity: 0,
      overseasReferencePriceMax: 12,
      overseasReferencePriceMin: 9,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "electrified",
      routeLabel: i18n.t("game:productionRoute.electrified"),
      unitBudgetCost: 5,
      unitOutput: 1,
      usageHint: i18n.t("game:demo.usageRubber", "终盘高值品。"),
    },
  ],
  routeSummaries: [
    {
      availableBatchesThisRound: 1,
      currentCapacity: 1,
      pendingCapacity: 0,
      routeId: "handicraft",
      routeLabel: i18n.t("game:productionRoute.handicraft"),
    },
    {
      availableBatchesThisRound: 0,
      currentCapacity: 0,
      pendingCapacity: 0,
      routeId: "mechanized",
      routeLabel: i18n.t("game:productionRoute.mechanized"),
    },
  ],
  techPoints: 0,
  techTree: {
    chains: [
      {
        chainId: "industrial",
        label: i18n.t("game:demo.chainIndustrial", "工业链"),
        techs: [
          { techId: "textile_tech", label: i18n.t("game:demo.techTextile", "纺织技术"), threshold: 3, progress: 0, effectiveThreshold: 3, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "tea_craft", label: i18n.t("game:demo.techTeaCraft", "茶道工艺"), threshold: 3, progress: 0, effectiveThreshold: 3, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "mining_dev", label: i18n.t("game:demo.techMining", "矿业开发"), threshold: 3, progress: 0, effectiveThreshold: 3, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "spinning_jenny", label: i18n.t("game:technology.spinning_jenny"), threshold: 5, progress: 0, effectiveThreshold: 5, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "steam_engine", label: i18n.t("game:technology.steam_engine"), threshold: 8, progress: 0, effectiveThreshold: 8, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "electrification", label: i18n.t("game:demo.techElectrification", "电气化"), threshold: 12, progress: 0, effectiveThreshold: 12, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
        ],
      },
      {
        chainId: "governance",
        label: i18n.t("game:demo.chainGovernance", "治理链"),
        techs: [
          { techId: "admin_reform", label: i18n.t("game:demo.techAdminReform", "行政改革"), threshold: 4, progress: 0, effectiveThreshold: 4, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "imperial_system", label: i18n.t("game:demo.techImperialSystem", "帝国体制"), threshold: 6, progress: 0, effectiveThreshold: 6, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "global_hegemony", label: i18n.t("game:demo.techGlobalHegemony", "全球霸权"), threshold: 10, progress: 0, effectiveThreshold: 10, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
        ],
      },
      {
        chainId: "commerce",
        label: i18n.t("game:demo.chainCommerce", "商业链"),
        techs: [
          { techId: "market_economy", label: i18n.t("game:demo.techMarketEconomy", "市场经济"), threshold: 3, progress: 0, effectiveThreshold: 3, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "consumer_society", label: i18n.t("game:demo.techConsumerSociety", "消费社会"), threshold: 5, progress: 0, effectiveThreshold: 5, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
        ],
      },
    ],
    researchFacilities: 1,
    facilityCost: 10,
    progressPerFacility: 2,
    breakthroughDieSides: 10,
    activeResearch: null,
  },
  upgradeOptions: [],
};
