import type { DecisionPlayerPhaseWorkspace } from "../../../types";

export const AUSTRIA_DECISION_DEMO_WORKSPACE: DecisionPlayerPhaseWorkspace = {
  activeEvents: [],
  budgetPools: {
    domesticMarket: 10,
    factory: 10,
    governmentFiscal: 15,
  },
  countryCode: "austria",
  countryLabel: "奥地利",
  domesticMarketActions: [],
  expansionOptions: [
    {
      capacityDelta: 1,
      lockedReason: null,
      maxQuantity: 1,
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 8,
    },
  ],
  governmentActions: {
    pointPurchaseCosts: {
      military: 6,
      tech: 2,
    },
    strategies: [
      {
        actionId: "expand_workshop",
        cost: 4,
        description: "扩建民间手工作坊，增加后续手工业产能。",
        label: "扩建作坊",
        lockedReason: null,
        effects: { handicraftCapacityDelta: 1 },
      },
      {
        actionId: "market_fair",
        cost: 5,
        description: "举办商品博览会，低成本扩大本回合国内承接量。",
        label: "博览会",
        lockedReason: null,
        effects: { domesticMarketCapacityDelta: 2 },
      },
      {
        actionId: "rural_development",
        cost: 6,
        description: "投资乡村基建，大幅扩大本回合国内承接量。",
        label: "乡村开发",
        lockedReason: null,
        effects: { domesticMarketCapacityDelta: 3 },
      },
      {
        actionId: "consumer_subsidy",
        cost: 8,
        description: "追加消费补贴，同时提高本回合国内承接量和收购价格。",
        label: "消费补贴",
        lockedReason: "需要研究「市场经济」",
        effects: { domesticMarketCapacityDelta: 2, domesticPriceBonusDelta: 1 },
      },
      {
        actionId: "import_substitution",
        cost: 7,
        description: "限制进口替代品，提高本回合国内承接量和收购价格。",
        label: "进口替代",
        lockedReason: "需要研究「市场经济」",
        effects: { domesticMarketCapacityDelta: 1, domesticPriceBonusDelta: 2 },
      },
      {
        actionId: "public_works",
        cost: 8,
        description: "投入公共工程，同时抬高本回合内需承接和价格。",
        label: "公共工程",
        lockedReason: "需要研究「消费社会」",
        effects: { domesticMarketCapacityDelta: 2, domesticPriceBonusDelta: 2 },
      },
      {
        actionId: "luxury_promotion",
        cost: 9,
        description: "培育高端消费市场，提高国内商品收购价格，但收益不再压过完整军事路线。",
        label: "奢侈品推广",
        lockedReason: "需要研究「消费社会」",
        effects: { domesticPriceBonusDelta: 2 },
      },
      {
        actionId: "infrastructure_investment",
        cost: 10,
        description: "投资基础设施，增加后续手工业产能。",
        label: "基础设施投资",
        lockedReason: "需要研究「消费社会」",
        effects: { handicraftCapacityDelta: 2 },
      },
      {
        actionId: "trade_hub",
        cost: 15,
        description: "建设临时商贸枢纽，本回合扩展海外市场承接能力。",
        label: "商贸枢纽",
        lockedReason: "需要研究「全球霸权」",
        effects: { overseasMarketCapacityDelta: 1 },
      },
      {
        actionId: "expand_research",
        cost: 10,
        description: "建设一所研究院，永久提高研究推进速度。",
        label: "建立研究院",
        lockedReason: null,
        effects: { researchFacilityDelta: { academy: 1 } },
      },
    ],
  },
  incomeAllocationRatio: {
    domesticMarket: 3,
    factory: 2.5,
    governmentFiscal: 4.5,
  },
  domesticMarketCapacity: 4,
  overseasMarketCapacity: 1,
  phase1Economy: {
    capacityByMode: { handicraft: 1 },
    rawMaterials: 3,
    goodsInventory: 2,
    productionModes: [],
    domesticDemand: 4,
    equilibriumPrice: 3,
    domesticBasePricePreview: 3,
    domesticPriceBeforeCap: 3,
    domesticPricePreview: 3,
    domesticPriceBonus: 0,
    overseasPriceBonus: 0,
    domesticPriceCeiling: 8,
    overseasPriceCeiling: 18,
    investmentPool: 10,
    incomeAllocationRatio: {
      domesticMarket: 3,
      factory: 2.5,
      governmentFiscal: 4.5,
    },
    marketMetrics: {},
    consumptionPool: 10,
  },
  militaryWorkspace: {
    militaryPoints: 1,
    army: {
      infantry: 1,
    },
    navy: {
      fleets: 0,
    },
    controlledRegions: 0,
    establishedDiplomacy: [],
    overseasCapacity: 1,
    regionAccessStatus: [
      {
        regionId: "africa",
        label: "非洲",
        accessLevel: "concession",
        isAccessible: true,
        lockReason: null,
        isDiplomacyEstablished: false,
        acceptedGoods: ["rubber", "cotton", "minerals"],
        priceMultiplier: 1,
        isColonized: false,
        controller: null,
      },
      {
        regionId: "middle_east",
        label: "中东",
        accessLevel: "concession",
        isAccessible: true,
        lockReason: null,
        isDiplomacyEstablished: false,
        acceptedGoods: ["oil", "tea"],
        priceMultiplier: 1,
        isColonized: false,
        controller: null,
      },
      {
        regionId: "europe",
        label: "欧洲",
        accessLevel: "open",
        isAccessible: true,
        lockReason: null,
        isDiplomacyEstablished: false,
        acceptedGoods: ["steel", "coal"],
        priceMultiplier: 1,
        isColonized: false,
        controller: null,
      },
    ],
    colonizationCapability: {
      isUnlocked: false,
      unlockCost: 10,
      militaryPointCost: 3,
      incomePerColonyPerRound: 5,
      maxColonizationsPerRound: 1,
    },
    colonizationOptions: [],
    oceanNodes: [],
    availableMilitaryActions: [
      {
        actionId: "naval_drill",
        label: "海军演练",
        cost: 1,
        maxPerRound: 2,
        description: "消耗军事点开展海军演练，扩展本轮海外市场承接力。",
        effects: { overseasMarketCapacityDelta: 1 },
      },
      {
        actionId: "recruit_infantry",
        label: "征募步兵",
        cost: 1,
        maxPerRound: 3,
        description: "消耗军事点征募步兵部队。",
        effects: { armyDelta: { infantry: 1 } },
      },
      {
        actionId: "train_artillery",
        label: "训练炮兵",
        cost: 2,
        maxPerRound: 1,
        description: "消耗军事点训练重型炮兵。",
        effects: { armyDelta: { artillery: 1 } },
      },
      {
        actionId: "colonial_expedition",
        label: "殖民远征",
        cost: 20,
        maxPerRound: 1,
        description: "组织大规模远征，强化海外控制与承接能力。",
        effects: { overseasMarketCapacityDelta: 2, controlledRegionsDelta: 1 },
      },
    ],
    availableDiplomacyActions: [
      {
        actionId: "establish_africa",
        label: "与非洲建交",
        cost: 7,
        targetRegion: "africa",
        targetRegionLabel: "非洲",
        description: "与非洲建立外交关系，永久开放贸易通道。",
        isEstablished: false,
      },
      {
        actionId: "establish_middle_east",
        label: "与中东建交",
        cost: 7,
        targetRegion: "middle_east",
        targetRegionLabel: "中东",
        description: "与中东建立外交关系，永久开放贸易通道。",
        isEstablished: false,
      },
    ],
  },
  researchWorkspace: {
    techPoints: 2,
    talentBranches: [
      {
        branchId: "industry",
        label: "工业",
        nodes: [
          {
            nodeId: "ind_basic_metallurgy",
            label: "工坊整顿",
            techPointCost: 1,
            description: "整顿分散工坊和账房流程，稳定扩大早期手工业产能。 效果：手工业产能 +1。",
            permanentEffects: { handicraftCapacityDelta: 1 },
            isUnlocked: false,
            canUnlock: true,
          },
        ],
      },
    ],
    unlockedTalentCount: 0,
  },
  militaryPoints: 1,
  nationalAbility: {
    abilityId: "ausgleich_1867",
    description: "本回合同时提升国内与海外承接能力。",
    isAvailable: true,
    label: "1867年妥协",
    requiresTargetIdeology: false,
  },
  newFactoryOptions: [
    {
      capacityDelta: 1,
      lockedReason: "预算不足",
      maxQuantity: 0,
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 12,
    },
  ],
  factoryActions: [
    {
      actionId: "factory_tax_contracting",
      label: "财政承包",
      cost: 0,
      description: "抽调工人与账房支援财政征收，本回合投料上限 -2，政府预算 +4。",
      lockedReason: null,
      effects: { phase1ProductionRawCapacityDelta: -2, governmentFiscalBudgetDelta: 4 },
    },
    {
      actionId: "factory_raw_procurement",
      label: "原料统购",
      cost: 3,
      description: "由工厂直接组织原料采购，立刻补充原材料。",
      lockedReason: null,
      effects: { rawMaterialsDelta: 4 },
    },
  ],
  productionOptions: [
    {
      domesticReferencePrice: 3,
      goodsId: "grain",
      label: "粮食",
      lockedReason: null,
      maxQuantity: 1,
      overseasReferencePriceMax: 5,
      overseasReferencePriceMin: 2,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 1,
      unitOutput: 1,
      usageHint: "稳内需、低风险。",
    },
    {
      domesticReferencePrice: 2,
      goodsId: "cotton",
      label: "棉花",
      lockedReason: "需要研究「纺织技术」",
      maxQuantity: 0,
      overseasReferencePriceMax: 7,
      overseasReferencePriceMin: 4,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 1,
      unitOutput: 1,
      usageHint: "早期出口原料。",
    },
    {
      domesticReferencePrice: 3,
      goodsId: "tea",
      label: "茶叶",
      lockedReason: "需要研究「茶道工艺」",
      maxQuantity: 0,
      overseasReferencePriceMax: 8,
      overseasReferencePriceMin: 5,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 2,
      unitOutput: 1,
      usageHint: "早期高外销。",
    },
    {
      domesticReferencePrice: 4,
      goodsId: "coal",
      label: "煤炭",
      lockedReason: "该国无该商品生产资格",
      maxQuantity: 0,
      overseasReferencePriceMax: 7,
      overseasReferencePriceMin: 4,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 2,
      unitOutput: 1,
      usageHint: "工业基础品。",
    },
    {
      domesticReferencePrice: 3,
      goodsId: "minerals",
      label: "矿产",
      lockedReason: null,
      maxQuantity: 1,
      overseasReferencePriceMax: 8,
      overseasReferencePriceMin: 5,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "handicraft",
      routeLabel: "手工业",
      unitBudgetCost: 2,
      unitOutput: 1,
      usageHint: "中性外销品。",
    },
    {
      domesticReferencePrice: 6,
      goodsId: "steel",
      label: "钢铁",
      lockedReason: "需要研究「珍妮纺织机」",
      maxQuantity: 0,
      overseasReferencePriceMax: 10,
      overseasReferencePriceMin: 7,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "mechanized",
      routeLabel: "机械化",
      unitBudgetCost: 3,
      unitOutput: 1,
      usageHint: "工业主力品。",
    },
    {
      domesticReferencePrice: 5,
      goodsId: "silk",
      label: "丝绸",
      lockedReason: "需要研究「珍妮纺织机」",
      maxQuantity: 0,
      overseasReferencePriceMax: 11,
      overseasReferencePriceMin: 8,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "mechanized",
      routeLabel: "机械化",
      unitBudgetCost: 3,
      unitOutput: 1,
      usageHint: "奢侈出口品。",
    },
    {
      domesticReferencePrice: 7,
      goodsId: "oil",
      label: "石油",
      lockedReason: "需要研究「蒸汽引擎」",
      maxQuantity: 0,
      overseasReferencePriceMax: 11,
      overseasReferencePriceMin: 8,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "steam",
      routeLabel: "蒸汽工业",
      unitBudgetCost: 4,
      unitOutput: 1,
      usageHint: "中后期高值品。",
    },
    {
      domesticReferencePrice: 8,
      goodsId: "rubber",
      label: "橡胶",
      lockedReason: "需要研究「电气化」",
      maxQuantity: 0,
      overseasReferencePriceMax: 12,
      overseasReferencePriceMin: 9,
      priceAdjustment: 0,
      priceTrend: "flat",
      routeId: "electrified",
      routeLabel: "电气工业",
      unitBudgetCost: 5,
      unitOutput: 1,
      usageHint: "终盘高值品。",
    },
  ],
  routeSummaries: [
    {
      availableBatchesThisRound: 1,
      currentCapacity: 1,
      pendingCapacity: 0,
      routeId: "handicraft",
      routeLabel: "手工业",
    },
    {
      availableBatchesThisRound: 0,
      currentCapacity: 0,
      pendingCapacity: 0,
      routeId: "mechanized",
      routeLabel: "机械化",
    },
  ],
  techPoints: 0,
  techTree: {
    chains: [
      {
        chainId: "industrial",
        label: "工业链",
        techs: [
          { techId: "textile_tech", label: "纺织技术", threshold: 3, progress: 0, effectiveThreshold: 3, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "tea_craft", label: "茶道工艺", threshold: 3, progress: 0, effectiveThreshold: 3, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "mining_dev", label: "矿业开发", threshold: 3, progress: 0, effectiveThreshold: 3, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "spinning_jenny", label: "珍妮纺织机", threshold: 5, progress: 0, effectiveThreshold: 5, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "steam_engine", label: "蒸汽引擎", threshold: 8, progress: 0, effectiveThreshold: 8, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "electrification", label: "电气化", threshold: 12, progress: 0, effectiveThreshold: 12, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
        ],
      },
      {
        chainId: "governance",
        label: "治理链",
        techs: [
          { techId: "admin_reform", label: "行政改革", threshold: 4, progress: 0, effectiveThreshold: 4, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "imperial_system", label: "帝国体制", threshold: 6, progress: 0, effectiveThreshold: 6, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "global_hegemony", label: "全球霸权", threshold: 10, progress: 0, effectiveThreshold: 10, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
        ],
      },
      {
        chainId: "commerce",
        label: "商业链",
        techs: [
          { techId: "market_economy", label: "市场经济", threshold: 3, progress: 0, effectiveThreshold: 3, isUnlocked: false, isActive: false, canResearch: true, isDiscovered: false, breakthroughAttempts: 0 },
          { techId: "consumer_society", label: "消费社会", threshold: 5, progress: 0, effectiveThreshold: 5, isUnlocked: false, isActive: false, canResearch: false, isDiscovered: false, breakthroughAttempts: 0 },
        ],
      },
    ],
    researchFacilities: 1,
    facilityCost: 10,
    progressPerFacility: 2,
    breakthroughDieSides: 10,
    activeResearch: null,
  },
  upgradeOptions: [],
};
